local data     = require("scripts.lib.data")

local guy_node = nil

function init(_)
	guy_node = gui.get_node("guy")
	gui.animate(guy_node, "color.w", 1.0, gui.EASING_LINEAR, 0.3, 0)
end

function on_message(_, message_id, _, _)
	if message_id == data.proxy.msg.enable_game then
		timer.delay(0.3, false, function()
			gui.animate(guy_node, "color.w", 0.0, gui.EASING_LINEAR, 0.3, 0.5, function()
				msg.post(data.proxy.script, data.proxy.msg.guy_removed)
			end)
		end)
	end
end
