embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"moving_platform\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 32.0\n"
  "  y: 8.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/components/atlas/game.atlas\"\n"
  "}\n"
  ""
}
